baseurl = "https://ivomarino.com/"
languageCode = "en-US"
title = "ivomarino.com"
paginate = 4
Copyright = "All rights reserved - 2026"
theme = "casper"
summaryLength = 150

[params]
  description = "Senior Platform Engineer / SRE with 15+ years building and operating production platforms, specializing in Kubernetes."
  cover = "img/main-01.jpg"

  author = "Ivo Marino"
  authorlocation = "Baar, Zug"
  authorwebsite = "https://ivomarino.com"
  bio = "Senior Platform Engineer / SRE with 15+ years building and operating production platforms, specializing in Kubernetes. Founder of Floads GmbH."

  # logo = "images/logo.png"
  rybbitSiteId = "b002b08656de"

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "ivomarino"
  twitterName = "ivomarino"

  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[markup.goldmark.renderer]
  unsafe = true
